version: 2

sphinx:
  configuration: docs/courseboard/conf.py

formats:
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/courseboard/theme.txt
