modLoader="pyminecraft"
loaderVersion="[1,)"
license='MIT'

[[mods]]
modId="examplemod" #mandatory
entryClass="com.rickaym.examplemod.ModClass"
version="${file.jarVersion}" #mandatory
displayName="Example mod." #mandatory
description='''
Example mod using the Python language provider'''

[[dependencies.examplemod]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
